language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
    allow_failures:
        - "nightly"

install:
    - pip install -r requirements.txt

before_script:
    - flake8

script: py.test
