language: python

python:
  - "3.4"
  - "3.5"

matrix:
  allow_failures:
    - "nightly"

branches:
  only:
    - master

install: pip install -r requirements.txt

before_script: flake8

script: pytest

after_success: coveralls
