language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  allow_failures:
    - python: "3.2"
    - python: "3.3"

branches:
  only:
    - master
    - develop

install: pip install -r requirements.txt

before_script: flake8 --exit-zero

script: pytest

after_success: coveralls
