language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

matrix:
  allow_failures:
    - "nightly"

branches:
  only:
    - master
    - develop

install: pip install -r requirements.txt

before_script: flake8 --exit-zero

script: pytest

after_success: coveralls
